"""
LVC v0.2 -- SINGLE-FILE STANDALONE Reproduction script
=======================================================

This is a fully self-contained reproduction script that combines:
  - The v0.1 likelihood backend (Pantheon+, BAO, distance priors, SH0ES,
    fitter, locked Lock-phi-A and theta-Gaussian forms)
  - The v0.2 self-consistency tests (mock generation, six tests, results)

No external LVC modules are required. Only standard Python scientific
stack: numpy, scipy, pandas.


What this file reproduces
-------------------------

The v0.2 working paper Phase 0 self-consistency tests, on synthetic data:

    Result A (theta-coordinate stability):
        Test 3 F1 bootstrap:  median z_c  = 0.6380, std = 0.0692
        Test 3 F2 bootstrap:  median th_c = 0.4811, std = 0.0481
        Test 6 F1 bootstrap:  median z_c  = 0.6145, std = 0.2854
        Test 6 F2 bootstrap:  median th_c = 0.4820, std = 0.0091
        Truth: 1/phi = 0.61803, ln(phi) = 0.48121

    Result B (v15 release shift = 1.46 sigma):
        Delta z_c (v15) / sigma_F1 = 0.101 / 0.0692 = 1.46

    Result C (single-bump family degeneracy):
        F1, F2, F3, F6 within Delta-chi^2 < 1 of each other on LVC mock.
        F4 (double-bump) and F5 (monotonic) rejected by Delta-chi^2 > 4.

For the v0.1 main reproduction (chi^2 = 1602.77, etc) on real data,
see lvc_v01.py (or lvc_v01_reproduce.py); the v0.1 backend is inlined
in this file but the v0.1 fitting driver is not.


Six self-consistency tests
--------------------------
    Test 1   null mock, single-seed family fits  (false-positive check)
    Test 1b  LVC mock, single-seed family fits   (recovery check)
    Test 2   family discrimination on LVC mock
    Test 3   bootstrap F1, F2 on LVC mock with full N=1738 likelihood
    Test 5   BAO position-shift sweep on null mock
    Test 5b  BAO position-shift sweep on LVC mock
    Test 6   PP-excluded bootstrap on LVC mock


Scope and discipline
--------------------
v0.2 records the outcome of self-consistency tests run on synthetic data
generated by the v0.1 reproduction code at the v0.1 best-fit cosmology.
Truth and fitter share the same numerical backend; correlated systematics
of the real DR1/DR2 BAO measurements are not modeled. The findings should
be regarded as self-consistency checks of the construction, subject to
confirmation on the real N=1738 dataset.


External data
-------------
The Pantheon+ data (~33 MB) and covariance must be available locally:
    Pantheon+SH0ES.dat
    Pantheon+SH0ES_STAT+SYS.cov

If absent, the script offers automatic git-based download from
github.com/PantheonPlusSH0ES/DataRelease (sub-directory
Pantheon+_Data/4_DISTANCES_AND_COVAR).

Set PANTHEONPLUS_DIR environment variable, or place files in ./PP_data/

Tests 5, 5b, 6 do NOT require Pantheon+ data (use --skip-pp).


Approximate runtime
-------------------
v0.2 self-consistency tests:
    --quick (default):     ~25 min
    --full (paper):        ~75 min
    --test 5b only:        ~5 min  (no PP)
    --tests 5,5b,6 only:   ~15 min (no PP, all tests fast)


Usage
-----
    python lvc_v02_standalone.py                  # Phase 0 default (quick)
    python lvc_v02_standalone.py --full           # Phase 0 paper precision
    python lvc_v02_standalone.py --test 3         # only Test 3
    python lvc_v02_standalone.py --tests 3,6      # Tests 3 and 6
    python lvc_v02_standalone.py --skip-pp        # skip PP-required tests
    python lvc_v02_standalone.py --help


Author          : LUMENPIXEL  (independent researcher, Busan, Korea)
Comp. assist.   : Claude (Anthropic)
Date            : May 2026
"""
from __future__ import annotations

import argparse
import contextlib
import json
import os
import subprocess
import sys
import time

import numpy as np
import pandas as pd
from scipy.integrate import quad, solve_ivp
from scipy.optimize import differential_evolution, minimize


# ============================================================================
# PART I.  v0.1 BACKEND
#   constants, BAO data tables, Pantheon+ loader, likelihood functions,
#   v0.1 functional forms (T_zGauss, T_thetaGauss), fitter helpers.
#   Inlined verbatim from lvc_v01.py.
# ============================================================================
# ============================================================================
# SECTION 1. CONSTANTS
# ============================================================================

C_KMS         = 299_792.458              # speed of light, km/s
THETA_STAR    = 0.010409                 # Planck 2018 acoustic angle
SIG_THETA_STAR = 3.1e-5
Z_STAR        = 1090.0                   # photon decoupling redshift
H0_SHOES      = 73.04                    # SH0ES (Riess+ 2022)
SIG_H0_SHOES  = 1.04

# Radiation density (T_CMB = 2.7255 K, N_eff = 3.046)
OMEGA_GAMMA_H2 = 2.473e-5
NEFF_STD       = 3.046
OMEGA_R_H2     = OMEGA_GAMMA_H2 * (1 + 7/8 * (4/11)**(4/3) * NEFF_STD)

# Pi, e, Phi
PI  = np.pi
E   = np.e
PHI = (1 + np.sqrt(5)) / 2.0
INV_PHI = 1.0 / PHI                       # 0.61803...

# Lock-phi-A parameters (v16 phenomenology, also used by LVC)
W_PHI_A = E / (5 * PI)                    # 0.17305

# LVC pendulum locked parameters (Axioms L3, L4)
THETA_C_LVC = np.log(PHI)                 # 0.48121  (= ln phi)
W_LVC       = E / (5 * PI)                # 0.17305  (= e / 5pi)
OMEGA_0_SQ  = 2.0 / W_LVC**2              # 50 pi^2 / e^2 = 66.7853
OMEGA_0     = np.sqrt(OMEGA_0_SQ)         # sqrt(2) * 5pi / e = 8.1722

# Planck 2018 compressed distance priors
# (Chen, Huang & Wang 2019, Table 1, "TT,TE,EE+lowE+lensing")
R_PLANCK   = 1.7493
LA_PLANCK  = 301.462
WB_PLANCK  = 0.02236
SIG_R, SIG_LA, SIG_WB = 0.0049, 0.090, 0.00015
CORR_DP = np.array([
    [ 1.0000,  0.4720, -0.6536],
    [ 0.4720,  1.0000, -0.3392],
    [-0.6536, -0.3392,  1.0000]])
SIG_DP = np.array([SIG_R, SIG_LA, SIG_WB])
COV_DP = CORR_DP * SIG_DP[:, None] * SIG_DP[None, :]
COVINV_DP = np.linalg.inv(COV_DP)

# Combined-likelihood total measurement count (=1738)
N_COMBINED = 1701 + 13 + 11 + 2 + 7 + 3 + 1


# ============================================================================
# SECTION 2. PANTHEON+ DATA LOADER (with auto-download)
# ============================================================================

PP_DIR = os.environ.get(
    "PANTHEONPLUS_DIR",
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "PP_data"))
PP_DAT = os.path.join(PP_DIR, "Pantheon+SH0ES.dat")
PP_COV = os.path.join(PP_DIR, "Pantheon+SH0ES_STAT+SYS.cov")


def auto_download_pp():
    """Sparse-checkout PP data from PantheonPlusSH0ES/DataRelease."""
    print(f"\nPantheon+ data not found at {PP_DIR}.")
    print("Attempting automatic download from GitHub...")
    print(f"  Target directory: {PP_DIR}")
    print(f"  Required disk:    ~33 MB")
    response = input("\nDownload now? [Y/n] ").strip().lower()
    if response and response != 'y':
        print("Aborted. To resume, either:")
        print("  (a) Set PANTHEONPLUS_DIR to a directory containing the files.")
        print("  (b) Manually clone:")
        print("      git clone --depth=1 --filter=blob:none --no-checkout \\")
        print("          https://github.com/PantheonPlusSH0ES/DataRelease.git")
        print("      cd DataRelease")
        print("      git sparse-checkout init --cone")
        print("      git sparse-checkout set 'Pantheon+_Data/4_DISTANCES_AND_COVAR'")
        print("      git checkout main")
        sys.exit(1)

    os.makedirs(PP_DIR, exist_ok=True)
    import tempfile
    with tempfile.TemporaryDirectory() as tmp:
        cmds = [
            ['git', 'clone', '--depth=1', '--filter=blob:none', '--no-checkout',
             'https://github.com/PantheonPlusSH0ES/DataRelease.git', 'DataRelease'],
            ['git', '-C', 'DataRelease', 'sparse-checkout', 'init', '--cone'],
            ['git', '-C', 'DataRelease', 'sparse-checkout', 'set',
             'Pantheon+_Data/4_DISTANCES_AND_COVAR'],
            ['git', '-C', 'DataRelease', 'checkout', 'main'],
        ]
        for cmd in cmds:
            print("  Running:", " ".join(cmd))
            r = subprocess.run(cmd, cwd=tmp, capture_output=True, text=True,
                               timeout=180)
            if r.returncode != 0:
                print("ERROR:", r.stderr)
                sys.exit(1)
        src = os.path.join(tmp, 'DataRelease', 'Pantheon+_Data',
                           '4_DISTANCES_AND_COVAR')
        for fname in ['Pantheon+SH0ES.dat', 'Pantheon+SH0ES_STAT+SYS.cov']:
            src_f = os.path.join(src, fname)
            dst_f = os.path.join(PP_DIR, fname)
            print(f"  Copying {fname} ...")
            with open(src_f, 'rb') as fi, open(dst_f, 'wb') as fo:
                fo.write(fi.read())
    print("Download complete.\n")


def load_pantheonplus():
    """Load PP data and full STAT+SYS covariance."""
    if not os.path.exists(PP_DAT) or not os.path.exists(PP_COV):
        auto_download_pp()
    df = pd.read_csv(PP_DAT, sep=r'\s+')
    is_calib = (df['IS_CALIBRATOR'].values == 1)
    out = dict(
        zHD     = df['zHD'].values,
        zHEL    = df['zHEL'].values,
        mB      = df['m_b_corr'].values,
        ceph    = df['CEPH_DIST'].values,
        is_calib= is_calib,
        N       = len(df),
    )
    with open(PP_COV) as f:
        first = f.readline().strip()
    Ncov = int(first)
    cov = np.loadtxt(PP_COV, skiprows=1).reshape((Ncov, Ncov))
    out['Cinv'] = np.linalg.inv(cov)
    return out


# ============================================================================
# SECTION 3. BACKGROUND COSMOLOGY
# ============================================================================

# Dense z-grid for line-of-sight integrals
_Z_GRID = np.concatenate([[0.0], np.geomspace(1e-3, 5.0, 200)])


def E_lcdm(z, Om):
    """Flat Lambda-CDM normalised Hubble rate."""
    return np.sqrt(Om*(1+z)**3 + (1-Om))


# ----------------------------------------------------------------------------
# Modulation factors
# ----------------------------------------------------------------------------
def T_zGauss(z, A, zc=INV_PHI, w=W_PHI_A):
    """v16 Lock-phi-A modulation: Gaussian on z."""
    return 1.0 + A * np.exp(-((z - zc)/w)**2)


def T_thetaGauss(z, A, theta_c=THETA_C_LVC, w=W_LVC):
    """LVC pendulum modulation: Gaussian on theta = ln(1+z).

    This is the closed-form solution of the LVC pendulum ODE
        v''(theta) + Omega^2(theta) * v = 0
    with Omega^2(theta) = (2/w^2) * [1 - 2*((theta-theta_c)/w)**2]
    and initial conditions v(theta_c) = A, v'(theta_c) = 0.
    """
    theta = np.log(1.0 + z)
    return 1.0 + A * np.exp(-((theta - theta_c)/w)**2)


# ----------------------------------------------------------------------------
# LVC Hubble rate: Friedmann equation with derived dark-energy density
# ----------------------------------------------------------------------------
def Omega_LVC(z, A, Om, theta_c=THETA_C_LVC, w=W_LVC):
    """Dimensionless dark-energy density of the LVC construction.

    The Friedmann equation of the construction is written as
        H^2(z) / H_0^2 = Om*(1+z)^3 + Omega_LVC(z)
    with no separate cosmological-constant term. Omega_LVC is derived from
    the modulation factor and recovers (1 - Om) in the A=0 limit.

    Definition:
        Omega_LVC(z) = [Om*(1+z)^3 + (1-Om)] * T(z)^2 - Om*(1+z)^3
    """
    T = T_thetaGauss(z, A, theta_c, w)
    return (Om*(1+z)**3 + (1-Om)) * T**2 - Om*(1+z)**3


def E_LVC_squared(z, A, Om, theta_c=THETA_C_LVC, w=W_LVC):
    """Normalised Hubble rate squared for the LVC construction:
       (H/H_0)^2 = Om*(1+z)^3 + Omega_LVC(z)
    Equivalent to E_lcdm(z)^2 * T(z)^2 by construction."""
    return Om*(1+z)**3 + Omega_LVC(z, A, Om, theta_c, w)


def comoving_dist_grid(H0, Om, T_func=None):
    """D_C(z) on _Z_GRID. T_func=None for Lambda-CDM, else callable."""
    if T_func is None:
        H = H0 * E_lcdm(_Z_GRID, Om)
    else:
        Tv = T_func(_Z_GRID)
        if np.min(Tv) < 0.4 or np.max(Tv) > 2.0:
            return None
        H = H0 * E_lcdm(_Z_GRID, Om) * Tv
    if np.any(H <= 0):
        return None
    integrand = C_KMS / H
    DC = np.zeros_like(_Z_GRID)
    DC[1:] = np.cumsum(0.5 * (integrand[1:] + integrand[:-1])
                       * np.diff(_Z_GRID))
    return DC


# ============================================================================
# SECTION 4. PANTHEON+ LIKELIHOOD
# ============================================================================
def chi2_panplus(H0, Om, T_func, pp):
    """Pantheon+ unbinned chi^2 with M_B profiled analytically."""
    DC = comoving_dist_grid(H0, Om, T_func)
    if DC is None:
        return 1e10, 0.0
    DM_at_zHD = np.interp(pp['zHD'], _Z_GRID, DC)
    mu_pred = np.where(
        pp['is_calib'],
        pp['ceph'],
        5*np.log10((1+pp['zHEL']) * DM_at_zHD) + 25)
    d = pp['mB'] - mu_pred
    ones = np.ones(pp['N'])
    Cinv = pp['Cinv']
    Cinv_d = Cinv @ d
    Cinv_1 = Cinv @ ones
    s11 = ones @ Cinv_1
    s1d = ones @ Cinv_d
    M_hat = s1d / s11
    r = d - M_hat
    return float(r @ Cinv @ r), float(M_hat)


# ============================================================================
# SECTION 5. BAO DATA TABLES (DR1, DR2, BOSS, eBOSS)
# ============================================================================

# DESI DR2 BAO (DESI Collaboration 2025)
DESI_DR2_DV = [(0.295, 7.942, 0.075)]      # BGS, isotropic
DESI_DR2_PAIR = [
    ('LRG1', 0.510, 13.587, 0.169, 21.863, 0.427, -0.475),
    ('LRG2', 0.706, 17.347, 0.180, 19.458, 0.332, -0.423),
    ('LRG3', 0.934, 21.574, 0.153, 17.641, 0.193, -0.425),
    ('QSO',  1.321, 27.605, 0.320, 14.178, 0.217, -0.437),
    ('ELG2', 1.484, 30.519, 0.758, 12.816, 0.513, -0.489),
    ('Lya',  2.330, 38.988, 0.531,  8.632, 0.101, -0.431),
]

# DESI DR1 BAO
DESI_DR1_DV = [(0.295, 7.93, 0.150)]
DESI_DR1_PAIR = [
    ('LRG1', 0.510, 13.62, 0.25, 20.98, 0.61, -0.445),
    ('LRG2', 0.706, 16.85, 0.32, 20.08, 0.60, -0.420),
    ('LRG3', 0.930, 21.71, 0.28, 17.88, 0.35, -0.389),
    ('ELG2', 1.317, 27.79, 0.69, 13.82, 0.42, -0.444),
    ('Lya',  2.330, 39.71, 0.94,  8.52, 0.17, -0.477),
]

# BOSS DR12 (Alam+ 2017)
BOSS_DM = [(0.38, 10.27, 0.15)]
BOSS_DH = [(0.38, 24.89, 0.58, -0.42)]

# eBOSS DR16 (Alam+ 2021)
EBOSS_DM_PAIRS = [
    ('eBOSS_LRG', 0.698, 17.86, 0.33, 19.33, 0.53, -0.40),
    ('eBOSS_QSO', 1.480, 30.21, 0.79, 13.23, 0.47, -0.40),
    ('eBOSS_Lya', 2.334, 37.60, 1.90,  8.93, 0.28, -0.45),
]
EBOSS_DV = [('eBOSS_ELG', 0.845, 18.33, 0.57)]


# ============================================================================
# SECTION 6. DISTANCE PRIORS (sound-horizon multiplicative calibration)
# ============================================================================
def _z_star_HS(Ob_h2, Om_h2):
    """Hu-Sugiyama 1996 fitting formula for z_*."""
    g1 = 0.0783 * Ob_h2**(-0.238) / (1 + 39.5 * Ob_h2**0.763)
    g2 = 0.560 / (1 + 21.1 * Ob_h2**1.81)
    return 1048 * (1 + 0.00124 * Ob_h2**(-0.738)) * (1 + g1 * Om_h2**g2)


def _R_lA_raw(H0, Om, Ob_h2, T_func=None):
    """Raw R, l_A, D_M(z*), r_s(z*) without calibration."""
    h = H0 / 100.0
    Om_h2 = Om * h * h
    z_star = _z_star_HS(Ob_h2, Om_h2)
    Or_frac = OMEGA_R_H2 / h**2

    if T_func is None:
        def H_E(z):
            return H0 * np.sqrt(Om*(1+z)**3 + Or_frac*(1+z)**4
                                + (1 - Om - Or_frac))
    else:
        def H_E(z):
            T_val = float(T_func(np.array([z]))[0])
            return H0 * np.sqrt(Om*(1+z)**3 + Or_frac*(1+z)**4
                                + (1 - Om - Or_frac) * T_val * T_val)

    DM_star, _ = quad(lambda z: C_KMS/H_E(z), 0, z_star, limit=400)
    rs, _ = quad(
        lambda z: 1.0/np.sqrt(3*(1 + 3*Ob_h2/(4*OMEGA_GAMMA_H2)/(1+z)))
                  * C_KMS/H_E(z),
        z_star, 1e6, limit=400)
    R_raw = np.sqrt(Om_h2) * DM_star * 100.0 / C_KMS
    lA_raw = PI * DM_star / rs
    return R_raw, lA_raw, DM_star, rs, z_star


# Calibration: at Planck fiducial flat Lambda-CDM, multiplicative factor
_R_AT_PLANCK, _LA_AT_PLANCK, _, _, _ = _R_lA_raw(67.36, 0.3153, 0.02237, None)
CAL_R = R_PLANCK / _R_AT_PLANCK
CAL_LA = LA_PLANCK / _LA_AT_PLANCK


def chi2_DP(H0, Om, Ob_h2, T_func=None):
    R_raw, lA_raw, _, _, _ = _R_lA_raw(H0, Om, Ob_h2, T_func)
    R_cal = R_raw * CAL_R
    lA_cal = lA_raw * CAL_LA
    x = np.array([R_cal, lA_cal, Ob_h2])
    xref = np.array([R_PLANCK, LA_PLANCK, WB_PLANCK])
    d = x - xref
    return float(d @ COVINV_DP @ d), float(R_cal), float(lA_cal)


def DM_at_zstar(H0, Om, Ob_h2, T_func=None):
    _, _, DM_star, _, _ = _R_lA_raw(H0, Om, Ob_h2, T_func)
    return DM_star


# ============================================================================
# SECTION 7. COMBINED BAO LIKELIHOOD
# ============================================================================
def chi2_bao_combined(H0, Om, T_func, rd):
    """DR1 + DR2 + BOSS + eBOSS BAO chi^2."""
    DC = comoving_dist_grid(H0, Om, T_func)
    if DC is None:
        return 1e10
    if T_func is None:
        H = H0 * E_lcdm(_Z_GRID, Om)
    else:
        H = H0 * E_lcdm(_Z_GRID, Om) * T_func(_Z_GRID)

    chi2 = 0.0

    # ---- DR2 BAO ----
    for z, DVo, sig in DESI_DR2_DV:
        DM = np.interp(z, _Z_GRID, DC)
        Hv = np.interp(z, _Z_GRID, H)
        DV = (z * DM**2 * C_KMS / Hv) ** (1/3)
        chi2 += ((DVo - DV / rd) / sig) ** 2
    for label, z, DMo, sDM, DHo, sDH, corr in DESI_DR2_PAIR:
        DMp = np.interp(z, _Z_GRID, DC) / rd
        DHp = C_KMS / np.interp(z, _Z_GRID, H) / rd
        cov = np.array([[sDM**2, corr * sDM * sDH],
                        [corr * sDM * sDH, sDH**2]])
        d = np.array([DMo - DMp, DHo - DHp])
        chi2 += d @ np.linalg.inv(cov) @ d

    # ---- DR1 BAO ----
    for z, DVo, sig in DESI_DR1_DV:
        DM = np.interp(z, _Z_GRID, DC)
        Hv = np.interp(z, _Z_GRID, H)
        DV = (z * DM**2 * C_KMS / Hv) ** (1/3)
        chi2 += ((DVo - DV / rd) / sig) ** 2
    for label, z, DMo, sDM, DHo, sDH, corr in DESI_DR1_PAIR:
        DMp = np.interp(z, _Z_GRID, DC) / rd
        DHp = C_KMS / np.interp(z, _Z_GRID, H) / rd
        cov = np.array([[sDM**2, corr * sDM * sDH],
                        [corr * sDM * sDH, sDH**2]])
        d = np.array([DMo - DMp, DHo - DHp])
        chi2 += d @ np.linalg.inv(cov) @ d

    # ---- BOSS DR12 ----
    for (z, DMo, sDM), (z2, DHo, sDH, corr) in zip(BOSS_DM, BOSS_DH):
        DMp = np.interp(z, _Z_GRID, DC) / rd
        DHp = C_KMS / np.interp(z, _Z_GRID, H) / rd
        cov = np.array([[sDM**2, corr * sDM * sDH],
                        [corr * sDM * sDH, sDH**2]])
        d = np.array([DMo - DMp, DHo - DHp])
        chi2 += d @ np.linalg.inv(cov) @ d

    # ---- eBOSS DR16 ----
    for label, z, DMo, sDM, DHo, sDH, corr in EBOSS_DM_PAIRS:
        DMp = np.interp(z, _Z_GRID, DC) / rd
        DHp = C_KMS / np.interp(z, _Z_GRID, H) / rd
        cov = np.array([[sDM**2, corr * sDM * sDH],
                        [corr * sDM * sDH, sDH**2]])
        d = np.array([DMo - DMp, DHo - DHp])
        chi2 += d @ np.linalg.inv(cov) @ d
    for label, z, DVo, sig in EBOSS_DV:
        DM = np.interp(z, _Z_GRID, DC)
        Hv = np.interp(z, _Z_GRID, H)
        DV = (z * DM**2 * C_KMS / Hv) ** (1/3)
        chi2 += ((DVo - DV / rd) / sig) ** 2

    return float(chi2)


def chi2_total_combined(H0, Om, Ob_h2, T_func, pp):
    """PP + (DR1+DR2)BAO + SH0ES + DP."""
    DM_star = DM_at_zstar(H0, Om, Ob_h2, T_func)
    rd = THETA_STAR * DM_star
    chi_pp, _ = chi2_panplus(H0, Om, T_func, pp)
    chi_bao = chi2_bao_combined(H0, Om, T_func, rd)
    chi_h = ((H0_SHOES - H0) / SIG_H0_SHOES) ** 2
    chi_dp, _, _ = chi2_DP(H0, Om, Ob_h2, T_func)
    return chi_pp + chi_bao + chi_h + chi_dp


# ============================================================================
# SECTION 8. FITTERS
# ============================================================================
def _de_nm(cost, bounds, seeds, maxiter=120, popsize=12, polish_iter=2500):
    """Differential evolution + Nelder-Mead polish, multi-seed."""
    best = (1e10, None)
    for sd in seeds:
        de = differential_evolution(cost, bounds, seed=sd, tol=1e-7,
                                    maxiter=maxiter, polish=False,
                                    popsize=popsize)
        nm = minimize(cost, de.x, method='Nelder-Mead',
                      options=dict(xatol=1e-8, fatol=1e-8, maxiter=polish_iter))
        if nm.fun < best[0]:
            best = (float(nm.fun), nm.x.copy())
    return best


def fit_LCDM(pp, seeds):
    """Fit Lambda-CDM (k=3): H0, Om, Ob_h2."""
    bounds = [(60, 80), (0.20, 0.45), (0.020, 0.025)]
    def cost(p):
        return chi2_total_combined(p[0], p[1], p[2], None, pp)
    return _de_nm(cost, bounds, seeds=seeds)


def fit_LockPhiA(pp, seeds):
    """Fit Lock-phi-A v16 (k=4): H0, Om, Ob_h2, A. z-Gaussian, locked zc, w."""
    bounds = [(60, 80), (0.20, 0.45), (0.020, 0.025), (-0.3, 0.3)]
    def cost(p):
        T = lambda z: T_zGauss(z, p[3])
        return chi2_total_combined(p[0], p[1], p[2], T, pp)
    return _de_nm(cost, bounds, seeds=seeds)


def fit_LVC(pp, seeds):
    """Fit LVC pendulum (k=4): H0, Om, Ob_h2, A. theta-Gaussian, locked theta_c, w."""
    bounds = [(60, 80), (0.20, 0.45), (0.020, 0.025), (-0.3, 0.3)]
    def cost(p):
        T = lambda z: T_thetaGauss(z, p[3])
        return chi2_total_combined(p[0], p[1], p[2], T, pp)
    return _de_nm(cost, bounds, seeds=seeds)


# ============================================================================
# SECTION 9. NUMERICAL ODE VERIFICATION (optional)
# ============================================================================
def verify_ode():
    """Numerical integration of the LVC pendulum ODE.

    ODE: v''(theta) + Omega^2(theta) * v = 0
         Omega^2(theta) = (2/w^2) * [1 - 2*((theta-theta_c)/w)**2]
    IC : v(theta_c) = A, v'(theta_c) = 0

    Verifies that the analytic Gaussian closed-form
         v(theta) = A * exp(-((theta-theta_c)/w)**2)
    is reproduced by direct integration to machine precision.
    """
    print("\n" + "=" * 70)
    print("ODE verification: numerical integration vs analytic Gaussian")
    print("=" * 70)

    A_test = 0.05
    theta_c = THETA_C_LVC
    w = W_LVC

    def rhs(theta, y):
        v, dv = y
        Om2 = (2.0/w**2) * (1.0 - 2.0*((theta - theta_c)/w)**2)
        return [dv, -Om2 * v]

    # Forward and backward from theta_c
    sol_f = solve_ivp(rhs, [theta_c, theta_c + 3*w], [A_test, 0.0],
                      method='DOP853', rtol=1e-12, atol=1e-15, dense_output=True)
    sol_b = solve_ivp(rhs, [theta_c, theta_c - 3*w], [A_test, 0.0],
                      method='DOP853', rtol=1e-12, atol=1e-15, dense_output=True)

    print(f"  theta_c = ln(phi)    = {theta_c:.8f}")
    print(f"  w       = e/(5 pi)   = {w:.8f}")
    print(f"  A       (test value) = {A_test}")
    print()
    print(f"  {'theta':>10} {'v_ODE':>14} {'v_analytic':>14} {'|diff|':>10}")
    print("  " + "-" * 50)
    max_err = 0.0
    for theta in np.linspace(theta_c - 2.5*w, theta_c + 2.5*w, 11):
        if theta >= theta_c:
            v_ode = float(sol_f.sol(theta)[0])
        else:
            v_ode = float(sol_b.sol(theta)[0])
        v_an = A_test * np.exp(-((theta - theta_c)/w)**2)
        err = abs(v_ode - v_an)
        max_err = max(max_err, err)
        print(f"  {theta:>10.5f} {v_ode:>14.10f} {v_an:>14.10f} {err:>10.2e}")
    print()
    print(f"  Maximum residual: {max_err:.2e}")
    if max_err < 1e-10:
        print("  Numerical ODE integration matches analytic closed form to 1e-10.")
    else:
        print(f"  WARNING: residual {max_err:.2e} larger than expected.")


# ============================================================================

# ============================================================================
# PART II.  v0.2 SELF-CONSISTENCY TESTS
#   mock data generation, family definitions F1-F6, six tests, main driver.
#   Inlined from lvc_v02_reproduce.py with all v01.* prefixes removed
#   (since the backend lives in PART I of this same file).
# ============================================================================
# ============================================================================
# SECTION 1. CONSTANTS AND TRUTH PARAMETERS
# ============================================================================

# v0.1 best-fit cosmology, used as the truth for LVC mock data
TRUTH_LVC = {
    "H0":   69.27,
    "Om":   0.288,
    "Obh2": 0.02237,
    "A":    0.0378,
}

# Null truth (LCDM, A=0)
TRUTH_NULL = {
    "H0":   70.40,
    "Om":   0.276,
    "Obh2": 0.02286,
    "A":    0.0,
}

# v15 release shift (used in Result B verification)
V15_DR1_ZC = 0.568
V15_DR2_ZC = 0.669
V15_RELEASE_SHIFT = V15_DR2_ZC - V15_DR1_ZC   # 0.101


# ============================================================================
# SECTION 2. FUNCTIONAL FAMILIES F1-F6
# ============================================================================

def T_F1_z_gaussian(z, A, zc, w):
    """F1: T(z) = 1 + A * exp(-((z-zc)/w)^2)."""
    return 1.0 + A * np.exp(-((np.asarray(z) - zc) / w) ** 2)


def T_F2_theta_gaussian(z, A, theta_c, w):
    """F2: T(z) = 1 + A * exp(-((theta-theta_c)/w)^2), theta = ln(1+z).
    The v0.1 functional form."""
    theta = np.log(1.0 + np.asarray(z))
    return 1.0 + A * np.exp(-((theta - theta_c) / w) ** 2)


def T_F3_skewed_z(z, A, zc, w_lo, w_hi):
    """F3: piecewise-Gaussian with separate widths below/above zc."""
    z = np.asarray(z, dtype=float)
    w = np.where(z < zc, w_lo, w_hi)
    return 1.0 + A * np.exp(-((z - zc) / w) ** 2)


def T_F4_double_z(z, A1, zc1, w1, A2, zc2, w2):
    """F4: two separate z-Gaussian bumps."""
    z = np.asarray(z, dtype=float)
    return 1.0 + A1 * np.exp(-((z - zc1) / w1) ** 2) \
               + A2 * np.exp(-((z - zc2) / w2) ** 2)


def T_F5_monotonic(z, A, zt, w):
    """F5: monotonic tanh transition."""
    z = np.asarray(z, dtype=float)
    return 1.0 + A * np.tanh((z - zt) / w)


def T_F6_narrow_z(z, A, zc, w):
    """F6: z-Gaussian with width restricted to w < 0.05 by bounds."""
    return T_F1_z_gaussian(z, A, zc, w)


FAMILIES = {
    "F1_zGauss":  ("F1 (z-Gaussian)",   3,
                   [(0.001, 0.20), (0.05, 1.50), (0.03, 0.50)]),
    "F2_thGauss": ("F2 (theta-Gauss)",  3,
                   [(0.001, 0.20), (0.05, 1.00), (0.03, 0.50)]),
    "F3_skewed":  ("F3 (skewed-z)",     4,
                   [(0.001, 0.20), (0.05, 1.50), (0.03, 0.50), (0.03, 0.50)]),
    "F4_double":  ("F4 (double-z)",     6,
                   [(0.001, 0.10), (0.05, 1.50), (0.03, 0.30),
                    (0.001, 0.10), (0.05, 1.50), (0.03, 0.30)]),
    "F5_mono":    ("F5 (monotonic)",    3,
                   [(0.001, 0.20), (0.05, 1.50), (0.03, 0.50)]),
    "F6_narrow":  ("F6 (narrow-z)",     3,
                   [(0.001, 0.20), (0.05, 1.50), (0.005, 0.05)]),
}

COSMO_BOUNDS = [(60.0, 80.0), (0.20, 0.45), (0.018, 0.028)]


def build_T_callable(family_name, params):
    """Construct the T(z) callable from family name and shape parameters."""
    if family_name == "F1_zGauss":
        A, zc, w = params
        return lambda z: T_F1_z_gaussian(z, A, zc, w)
    elif family_name == "F2_thGauss":
        A, thc, w = params
        return lambda z: T_F2_theta_gaussian(z, A, thc, w)
    elif family_name == "F3_skewed":
        A, zc, w_lo, w_hi = params
        return lambda z: T_F3_skewed_z(z, A, zc, w_lo, w_hi)
    elif family_name == "F4_double":
        A1, zc1, w1, A2, zc2, w2 = params
        return lambda z: T_F4_double_z(z, A1, zc1, w1, A2, zc2, w2)
    elif family_name == "F5_mono":
        A, zt, w = params
        return lambda z: T_F5_monotonic(z, A, zt, w)
    elif family_name == "F6_narrow":
        A, zc, w = params
        return lambda z: T_F6_narrow_z(z, A, zc, w)
    else:
        raise ValueError(f"unknown family {family_name}")


# ============================================================================
# SECTION 3. SYNTHETIC DATA GENERATION
# ============================================================================
#
# Approach: v0.1's BAO data lives as module-level tuples; mock generation
# replaces those tuples in place via a context manager. Pantheon+ mock is
# returned as a dict mirroring v0.1's load_pantheonplus() output.

def _derive_rd(H0, Om, Obh2, T_func=None):
    """Derive r_d from Planck theta* via geometric construction.
    DM_at_zstar in v0.1 takes (H0, Om, Ob_h2, T_func=None)."""
    DMz = DM_at_zstar(H0, Om, Obh2, T_func)
    return THETA_STAR * DMz


def _build_mock_pp(truth_params, T_truth, rng):
    """Generate a mock Pantheon+ dataset matching v0.1's load_pantheonplus()
    return format.

    v0.1 uses keys: zHD, zHEL, mB, ceph, is_calib, N, Cinv. The likelihood
    chi2_panplus computes mu_pred from (zHD, zHEL) for non-calibrators or
    uses ceph directly for Cepheid hosts, then forms residual d = mB - mu_pred
    and contracts with Cinv (with M_B profiled analytically).

    To mock self-consistently, we compute the truth mu_pred at each SN, draw
    Gaussian noise from the full STAT+SYS covariance, and store the noisy
    magnitudes back into mB. Calibrators keep their ceph values unchanged
    (the calibration anchor is the SH0ES distance ladder, mocked separately
    via the SH0ES H0 prior).
    """
    pp = load_pantheonplus()

    zHD = pp["zHD"]
    zHEL = pp["zHEL"]
    is_calib = pp["is_calib"]
    ceph = pp["ceph"]
    Cinv = pp["Cinv"]
    n = pp["N"]

    H0 = truth_params["H0"]
    Om = truth_params["Om"]
    DC_grid = comoving_dist_grid(H0, Om, T_truth)
    if DC_grid is None:
        raise RuntimeError("comoving_dist_grid returned None at truth params")

    DM_at_zHD = np.interp(zHD, _Z_GRID, DC_grid)
    # Predicted mu: calibrators take ceph anchor, others take 5log10(dL)+25
    mu_pred = np.where(
        is_calib,
        ceph,
        5.0 * np.log10((1.0 + zHEL) * DM_at_zHD) + 25.0,
    )

    # The truth m_B before noise: m_B = mu_pred + M_B. We adopt M_B = -19.253
    # (standard SH0ES anchor); since chi2_panplus profiles M_B analytically,
    # the absolute value drops out and only the residual structure matters.
    M_B_truth = -19.253
    mB_truth = mu_pred + M_B_truth

    # Draw correlated noise from the full STAT+SYS covariance C = inv(Cinv).
    # For numerical stability we solve L @ L.T = C via Cholesky on the
    # explicit inverse. The 1701x1701 inversion is one-time per fit and
    # cached implicitly by Cholesky reuse upstream.
    cov = np.linalg.inv(Cinv)
    cov = 0.5 * (cov + cov.T)  # symmetrize against round-off
    # Tiny ridge for positive-definiteness under finite-precision inversion
    L = np.linalg.cholesky(cov + 1e-12 * np.eye(n))
    eps = L @ rng.standard_normal(n)

    pp_mock = dict(pp)
    pp_mock["mB"] = mB_truth + eps
    return pp_mock


def _build_mock_bao_tables(truth_params, T_truth, rng):
    """Generate mock BAO tables matching v0.1's data-tuple format.

    Returns dict {var_name: new_table} keyed by v0.1 module variable names.
    """
    H0 = truth_params["H0"]
    Om = truth_params["Om"]
    Obh2 = truth_params["Obh2"]
    rd = _derive_rd(H0, Om, Obh2, T_truth)
    Z_GRID = _Z_GRID
    DC_grid = comoving_dist_grid(H0, Om, T_truth)
    H_grid = H0 * E_lcdm(Z_GRID, Om)
    if T_truth is not None:
        H_grid = H_grid * T_truth(Z_GRID)

    def DM_at(z): return float(np.interp(z, Z_GRID, DC_grid))
    def DH_at(z): return C_KMS / float(np.interp(z, Z_GRID, H_grid))
    def DV_at(z):
        DM = DM_at(z)
        Hv = float(np.interp(z, Z_GRID, H_grid))
        return (z * DM ** 2 * C_KMS / Hv) ** (1.0 / 3.0)

    out = {}

    def patch_pair_table(orig):
        new = []
        for entry in orig:
            label, z, _DMo, sDM, _DHo, sDH, corr = entry
            mean = np.array([DM_at(z) / rd, DH_at(z) / rd])
            cov = np.array([[sDM ** 2, corr * sDM * sDH],
                            [corr * sDM * sDH, sDH ** 2]])
            L = np.linalg.cholesky(cov + 1e-12 * np.eye(2))
            eps = L @ rng.standard_normal(2)
            new.append((label, z, mean[0] + eps[0], sDM,
                        mean[1] + eps[1], sDH, corr))
        return new

    def patch_dv_table(orig):
        new = []
        for entry in orig:
            if len(entry) == 3:
                z, _DVo, sig = entry
                noise = sig * rng.standard_normal()
                new.append((z, DV_at(z) / rd + noise, sig))
            else:
                label, z, _DVo, sig = entry
                noise = sig * rng.standard_normal()
                new.append((label, z, DV_at(z) / rd + noise, sig))
        return new

    out["DESI_DR2_PAIR"]  = patch_pair_table(DESI_DR2_PAIR)
    out["DESI_DR2_DV"]    = patch_dv_table(DESI_DR2_DV)
    out["DESI_DR1_PAIR"]  = patch_pair_table(DESI_DR1_PAIR)
    out["DESI_DR1_DV"]    = patch_dv_table(DESI_DR1_DV)
    out["EBOSS_DM_PAIRS"] = patch_pair_table(EBOSS_DM_PAIRS)
    out["EBOSS_DV"]       = patch_dv_table(EBOSS_DV)

    # BOSS is split between BOSS_DM and BOSS_DH in v0.1
    boss_dm_new, boss_dh_new = [], []
    for (z1, _DMo, sDM), (z2, _DHo, sDH, corr) in zip(BOSS_DM, BOSS_DH):
        mean = np.array([DM_at(z1) / rd, DH_at(z2) / rd])
        cov = np.array([[sDM ** 2, corr * sDM * sDH],
                        [corr * sDM * sDH, sDH ** 2]])
        L = np.linalg.cholesky(cov + 1e-12 * np.eye(2))
        eps = L @ rng.standard_normal(2)
        boss_dm_new.append((z1, mean[0] + eps[0], sDM))
        boss_dh_new.append((z2, mean[1] + eps[1], sDH, corr))
    out["BOSS_DM"] = boss_dm_new
    out["BOSS_DH"] = boss_dh_new

    return out


@contextlib.contextmanager
def _patched_v01(bao_overrides=None, dp_overrides=None):
    """Temporarily replace BAO tables and DP target means at module scope.
    In the merged standalone file, the "backend" is this module itself."""
    self_mod = sys.modules[__name__]
    saved = {}
    if bao_overrides is not None:
        for name, new in bao_overrides.items():
            saved[name] = getattr(self_mod, name)
            setattr(self_mod, name, new)
    if dp_overrides is not None:
        saved["R_PLANCK"]  = self_mod.R_PLANCK
        saved["LA_PLANCK"] = self_mod.LA_PLANCK
        saved["WB_PLANCK"] = self_mod.WB_PLANCK
        self_mod.R_PLANCK  = dp_overrides[0]
        self_mod.LA_PLANCK = dp_overrides[1]
        self_mod.WB_PLANCK = dp_overrides[2]
    try:
        yield
    finally:
        for name, old in saved.items():
            setattr(self_mod, name, old)


def generate_mock(truth_params, seed=0, lvc_truth=True, with_pp=True):
    """Generate a complete synthetic dataset.

    Returns:
        bao_overrides : dict for v0.1 module-variable monkey-patching
        pp_mock       : mock Pantheon+ dict (or None)
        dp_mock       : mock distance-prior 3-vector
        h0_mock       : mock SH0ES H0 measurement (scalar)
    """
    rng = np.random.default_rng(seed)

    H0 = truth_params["H0"]
    A = truth_params["A"]

    if lvc_truth and A != 0:
        T_truth = lambda z: T_F2_theta_gaussian(z, A, THETA_C_LVC, W_LVC)
    else:
        T_truth = None  # treat as identity in v0.1's convention

    bao_overrides = _build_mock_bao_tables(truth_params, T_truth, rng)
    pp_mock = _build_mock_pp(truth_params, T_truth, rng) if with_pp else None

    # DP mock: target should be the model prediction at truth cosmology +
    # truth modulation, not the published Planck means. This keeps the mock
    # self-consistent with the LVC truth.
    _, R_truth, lA_truth = chi2_DP(H0, truth_params["Om"],
                                       truth_params["Obh2"], T_truth)
    dp_truth_means = np.array([R_truth, lA_truth, truth_params["Obh2"]])
    L_dp = np.linalg.cholesky(COV_DP)
    dp_mock = dp_truth_means + L_dp @ rng.standard_normal(3)

    h0_mock = H0 + SIG_H0_SHOES * rng.standard_normal()

    return bao_overrides, pp_mock, dp_mock, h0_mock


# ============================================================================
# SECTION 4. LIKELIHOOD ASSEMBLY ON MOCK DATA
# ============================================================================

def chi2_mock(params, family_name, bao_overrides, pp_mock, dp_mock, h0_mock,
              include_pp=True):
    """Total chi^2 for a given family fit on the synthetic dataset."""
    H0, Om, Obh2 = params[:3]
    T_callable = build_T_callable(family_name, params[3:])

    chi2 = 0.0

    with _patched_v01(bao_overrides=bao_overrides, dp_overrides=dp_mock):
        rd = _derive_rd(H0, Om, Obh2, T_callable)
        chi2 += chi2_bao_combined(H0, Om, T_callable, rd)
        # chi2_DP returns (chi2, R_model, lA_model); we only need the chi2
        dp_result = chi2_DP(H0, Om, Obh2, T_callable)
        chi2 += dp_result[0] if isinstance(dp_result, tuple) else dp_result
        chi2 += ((H0 - h0_mock) / SIG_H0_SHOES) ** 2
        if include_pp and pp_mock is not None:
            pp_result = chi2_panplus(H0, Om, T_callable, pp_mock)
            chi2 += pp_result[0] if isinstance(pp_result, tuple) else pp_result

    return float(chi2)


# ============================================================================
# SECTION 5. FITTER
# ============================================================================

def fit_family(bao_overrides, pp_mock, dp_mock, h0_mock,
               family_name, include_pp=True, n_seeds=3,
               de_iter=80, popsize=15, polish=True, verbose=False):
    """DE + Nelder-Mead fit of a functional family to the mock data."""
    fam_label, n_shape, shape_bounds = FAMILIES[family_name]
    bounds = list(COSMO_BOUNDS) + list(shape_bounds)

    def neg_lnL(p):
        try:
            return chi2_mock(p, family_name, bao_overrides,
                             pp_mock, dp_mock, h0_mock, include_pp=include_pp)
        except Exception:
            return 1e10

    best_chi2 = np.inf
    best_x = None
    t0 = time.time()
    for s in range(n_seeds):
        result = differential_evolution(
            neg_lnL, bounds,
            seed=s, maxiter=de_iter, popsize=popsize,
            tol=1e-7, mutation=(0.5, 1.5), recombination=0.7,
            polish=False, init='sobol')
        if polish:
            result = minimize(neg_lnL, result.x, method='Nelder-Mead',
                              options={'xatol': 1e-5, 'fatol': 1e-4,
                                       'maxiter': 2000})
        if result.fun < best_chi2:
            best_chi2 = result.fun
            best_x = result.x
        if verbose:
            print(f"    seed {s}: chi2 = {result.fun:.3f}")

    return dict(family=family_name, chi2=float(best_chi2),
                params=best_x.tolist(), time=time.time() - t0)


# ============================================================================
# SECTION 6. THE SIX TESTS
# ============================================================================

def run_test_1_null(args):
    """Test 1: null mock, single-seed family fits. False-positive check."""
    print("\n" + "=" * 70)
    print("TEST 1: null mock, single-seed family fits")
    print("=" * 70)
    bao, pp, dp, h0 = generate_mock(TRUTH_NULL, seed=0, lvc_truth=False)
    results = {}
    for fam in ["F1_zGauss", "F2_thGauss"]:
        r = fit_family(bao, pp, dp, h0, fam, include_pp=True,
                       n_seeds=args.n_seeds_per_fit, de_iter=args.de_iter)
        results[fam] = r
        label = FAMILIES[fam][0]
        print(f"  {label}: chi2 = {r['chi2']:.3f}, A = {r['params'][3]:+.4f}")
    return results


def run_test_1b_lvc(args):
    """Test 1b: LVC mock, single-seed family fits. Recovery check."""
    print("\n" + "=" * 70)
    print("TEST 1b: LVC mock, single-seed family fits")
    print("=" * 70)
    bao, pp, dp, h0 = generate_mock(TRUTH_LVC, seed=0, lvc_truth=True)
    results = {}
    for fam in ["F1_zGauss", "F2_thGauss"]:
        r = fit_family(bao, pp, dp, h0, fam, include_pp=True,
                       n_seeds=args.n_seeds_per_fit, de_iter=args.de_iter)
        results[fam] = r
        label = FAMILIES[fam][0]
        print(f"  {label}: chi2 = {r['chi2']:.3f}, A = {r['params'][3]:+.4f}, "
              f"pos = {r['params'][4]:.4f}")
    print(f"  Truth: A = {TRUTH_LVC['A']:+.4f}, "
          f"1/phi = {1 / PHI:.4f}, ln(phi) = {THETA_C_LVC:.4f}")
    return results


def run_test_2_family_disc(args):
    """Test 2: family discrimination on the LVC mock."""
    print("\n" + "=" * 70)
    print("TEST 2: family discrimination on LVC mock")
    print("=" * 70)
    bao, pp, dp, h0 = generate_mock(TRUTH_LVC, seed=0, lvc_truth=True)
    results = {}
    for fam in FAMILIES.keys():
        r = fit_family(bao, pp, dp, h0, fam, include_pp=True,
                       n_seeds=args.n_seeds_per_fit, de_iter=args.de_iter)
        results[fam] = r
        label, n_shape, _ = FAMILIES[fam]
        k = 3 + n_shape
        bic = r["chi2"] + k * np.log(N_COMBINED)
        print(f"  {label:20s}: k={k}, chi2 = {r['chi2']:.3f}, BIC = {bic:.3f}")

    best_chi2 = min(r["chi2"] for r in results.values())
    print()
    print(f"  Best chi2 = {best_chi2:.3f}")
    print("  Family               Delta-chi2 from best")
    for fam, r in sorted(results.items(), key=lambda x: x[1]["chi2"]):
        d = r["chi2"] - best_chi2
        verdict = "OK" if d < 1.0 else ("near" if d < 4.0 else "REJECTED")
        print(f"    {fam:18s} {d:+7.3f}   {verdict}")
    return results


def run_test_3_bootstrap(args):
    """Test 3: bootstrap of F1 and F2 on LVC mock with full likelihood."""
    print("\n" + "=" * 70)
    print(f"TEST 3: bootstrap of F1, F2 on LVC mock (n_boot = {args.n_boot})")
    print("=" * 70)
    results = {"F1_zGauss":  {"chi2": [], "A": [], "zc": [], "w": []},
               "F2_thGauss": {"chi2": [], "A": [], "thc": [], "w": []}}

    for seed in range(args.n_boot):
        print(f"  seed {seed:2d}", end=": ", flush=True)
        bao, pp, dp, h0 = generate_mock(TRUTH_LVC, seed=seed, lvc_truth=True)
        for fam in ["F1_zGauss", "F2_thGauss"]:
            r = fit_family(bao, pp, dp, h0, fam, include_pp=True,
                           n_seeds=args.n_seeds_per_fit, de_iter=args.de_iter)
            results[fam]["chi2"].append(r["chi2"])
            results[fam]["A"].append(r["params"][3])
            if fam == "F1_zGauss":
                results[fam]["zc"].append(r["params"][4])
                results[fam]["w"].append(r["params"][5])
            else:
                results[fam]["thc"].append(r["params"][4])
                results[fam]["w"].append(r["params"][5])
        print(f"F1 zc={results['F1_zGauss']['zc'][-1]:.4f}, "
              f"F2 thc={results['F2_thGauss']['thc'][-1]:.4f}", flush=True)

    print()
    print("  Summary (Result A — Test 3):")
    f1_zc  = np.array(results["F1_zGauss"]["zc"])
    f2_thc = np.array(results["F2_thGauss"]["thc"])
    print(f"    F1 (z-Gauss):  median z_c  = {np.median(f1_zc):.4f}, "
          f"std = {np.std(f1_zc):.4f}    (paper: 0.6380, 0.0692)")
    print(f"    F2 (th-Gauss): median th_c = {np.median(f2_thc):.4f}, "
          f"std = {np.std(f2_thc):.4f}    (paper: 0.4811, 0.0481)")
    print(f"    Truth: 1/phi = {1 / PHI:.4f}, ln(phi) = {THETA_C_LVC:.4f}")

    sigma_F1 = float(np.std(f1_zc))
    sigma_units = V15_RELEASE_SHIFT / sigma_F1 if sigma_F1 > 0 else float("nan")
    print()
    print("  Result B — v15 release shift in noise units:")
    print(f"    Delta z_c (v15) = {V15_DR2_ZC:.3f} - {V15_DR1_ZC:.3f} = "
          f"{V15_RELEASE_SHIFT:.3f}")
    print(f"    sigma_F1 (Test 3) = {sigma_F1:.4f}")
    print(f"    Delta z_c / sigma_F1 = {sigma_units:.2f} sigma    (paper: 1.46)")
    return results


def run_test_5_pulling(args, lvc_truth=False):
    """Test 5 / 5b: BAO-position-shift sweep, BAO+DP+SH0ES only."""
    label = "5b" if lvc_truth else "5"
    truth = TRUTH_LVC if lvc_truth else TRUTH_NULL
    print("\n" + "=" * 70)
    print(f"TEST {label}: BAO-position-shift sweep, "
          f"{'LVC' if lvc_truth else 'null'} truth")
    print("=" * 70)
    deltas = [-0.10, -0.05, 0.0, +0.05, +0.10]
    results = []
    bao_base, _, dp_base, h0_base = generate_mock(
        truth, seed=42, lvc_truth=lvc_truth, with_pp=False)
    for dz in deltas:
        # Apply z-shift to all BAO tables (variable layouts handled by length)
        bao_shifted = {}
        for k, table in bao_base.items():
            new = []
            for entry in table:
                if len(entry) == 7:                     # PAIR table
                    label_, z, DM, sDM, DH, sDH, corr = entry
                    new.append((label_, z + dz, DM, sDM, DH, sDH, corr))
                elif len(entry) == 4 and isinstance(entry[0], str):  # eBOSS DV
                    label_, z, DV, sig = entry
                    new.append((label_, z + dz, DV, sig))
                elif len(entry) == 4:                   # BOSS_DH
                    z, DH, sig, corr = entry
                    new.append((z + dz, DH, sig, corr))
                elif len(entry) == 3:                   # DESI_DV or BOSS_DM
                    z, val, sig = entry
                    new.append((z + dz, val, sig))
                else:
                    new.append(entry)
            bao_shifted[k] = new
        r = fit_family(bao_shifted, None, dp_base, h0_base,
                       "F1_zGauss", include_pp=False,
                       n_seeds=args.n_seeds_per_fit, de_iter=args.de_iter)
        zc_fit = r["params"][4]
        results.append({"delta_z": dz, "f1_zc": zc_fit, "f1_A": r["params"][3]})
        print(f"  delta_z = {dz:+.2f}: F1 zc = {zc_fit:.4f}, "
              f"A = {r['params'][3]:+.4f}")

    dzs = np.array([r["delta_z"] for r in results])
    zcs = np.array([r["f1_zc"]   for r in results])
    if len(dzs) > 1:
        slope = float(np.polyfit(dzs, zcs, 1)[0])
        verdict = "~ 0, no pulling" if abs(slope) < 0.1 else "BAO pulling detected"
        print(f"  Linear slope dz_c/d(delta_z) = {slope:+.3f}  ({verdict})")
        print("  Paper value (Test 5b): -0.022")
    return results


def run_test_6_no_pp(args):
    """Test 6: PP-excluded bootstrap on LVC mock."""
    print("\n" + "=" * 70)
    print(f"TEST 6: PP-excluded bootstrap on LVC mock (n = {args.n_boot_t6})")
    print("=" * 70)
    results = {"F1_zGauss":  {"chi2": [], "A": [], "zc": []},
               "F2_thGauss": {"chi2": [], "A": [], "thc": []}}

    for seed in range(args.n_boot_t6):
        bao, _, dp, h0 = generate_mock(TRUTH_LVC, seed=seed,
                                       lvc_truth=True, with_pp=False)
        for fam in ["F1_zGauss", "F2_thGauss"]:
            r = fit_family(bao, None, dp, h0, fam, include_pp=False,
                           n_seeds=args.n_seeds_per_fit, de_iter=args.de_iter)
            results[fam]["chi2"].append(r["chi2"])
            results[fam]["A"].append(r["params"][3])
            if fam == "F1_zGauss":
                results[fam]["zc"].append(r["params"][4])
            else:
                results[fam]["thc"].append(r["params"][4])
        print(f"  seed {seed}: F1 zc = {results['F1_zGauss']['zc'][-1]:.4f}, "
              f"F2 thc = {results['F2_thGauss']['thc'][-1]:.4f}", flush=True)

    print()
    print("  Summary (Result A — Test 6):")
    f1_zc  = np.array(results["F1_zGauss"]["zc"])
    f2_thc = np.array(results["F2_thGauss"]["thc"])
    print(f"    F1 (z-Gauss):  median z_c  = {np.median(f1_zc):.4f}, "
          f"std = {np.std(f1_zc):.4f}    (paper: 0.6145, 0.2854)")
    print(f"    F2 (th-Gauss): median th_c = {np.median(f2_thc):.4f}, "
          f"std = {np.std(f2_thc):.4f}    (paper: 0.4820, 0.0091)")
    print(f"    Truth: 1/phi = {1 / PHI:.4f}, ln(phi) = {THETA_C_LVC:.4f}")
    return results


# ============================================================================
# SECTION 7. MAIN DRIVER
# ============================================================================

def _walk_for_json(d):
    """Recursively cast numpy types to native Python for JSON serialisation."""
    if isinstance(d, dict):
        return {k: _walk_for_json(v) for k, v in d.items()}
    if isinstance(d, list):
        return [_walk_for_json(x) for x in d]
    if isinstance(d, np.ndarray):
        return d.tolist()
    if isinstance(d, np.floating):
        return float(d)
    if isinstance(d, np.integer):
        return int(d)
    return d


def main():
    parser = argparse.ArgumentParser(
        description="LVC v0.2 reproduction script.",
        formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--quick", action="store_true", default=True,
                        help="quick mode: short bootstraps (default)")
    parser.add_argument("--full", action="store_true",
                        help="paper precision: longer bootstraps and more seeds")
    parser.add_argument("--test", type=str, default=None,
                        help="run only one test (1, 1b, 2, 3, 5, 5b, 6)")
    parser.add_argument("--tests", type=str, default=None,
                        help="run a subset of tests (comma-separated, e.g. 3,6)")
    parser.add_argument("--skip-pp", action="store_true",
                        help="skip tests that require Pantheon+ data")
    parser.add_argument("--out", type=str, default="lvc_v02_results.json",
                        help="output JSON file (default: lvc_v02_results.json)")
    args = parser.parse_args()

    if args.full:
        args.n_boot     = 10
        args.n_boot_t6  = 5
        args.n_seeds_per_fit = 3
        args.de_iter   = 100
        mode = "full (paper precision)"
    else:
        args.n_boot     = 4
        args.n_boot_t6  = 3
        args.n_seeds_per_fit = 2
        args.de_iter   = 60
        mode = "quick"

    if args.test is not None:
        run_set = {args.test}
    elif args.tests is not None:
        run_set = set(args.tests.split(","))
    else:
        run_set = {"1", "1b", "2", "3", "5", "5b", "6"}

    print("=" * 70)
    print(f"LVC v0.2 reproduction script — {mode} mode")
    print("=" * 70)
    print(f"  Bootstrap depth:     Test 3 = {args.n_boot}, Test 6 = {args.n_boot_t6}")
    print(f"  Seeds per fit:       {args.n_seeds_per_fit}")
    print(f"  DE iterations:       {args.de_iter}")
    print(f"  Tests to run:        {sorted(run_set)}")
    print(f"  Output file:         {args.out}")

    pp_required = {"1", "1b", "2", "3"}
    if args.skip_pp:
        run_set = run_set - pp_required
        print(f"  --skip-pp: removed PP-required tests, running {sorted(run_set)}")

    t_start = time.time()
    results = {}

    if "1" in run_set:
        results["test_1_null"] = run_test_1_null(args)
    if "1b" in run_set:
        results["test_1b_lvc"] = run_test_1b_lvc(args)
    if "2" in run_set:
        results["test_2_family"] = run_test_2_family_disc(args)
    if "3" in run_set:
        results["test_3_bootstrap"] = run_test_3_bootstrap(args)
    if "5" in run_set:
        results["test_5_pulling_null"] = run_test_5_pulling(args, lvc_truth=False)
    if "5b" in run_set:
        results["test_5b_pulling_lvc"] = run_test_5_pulling(args, lvc_truth=True)
    if "6" in run_set:
        results["test_6_no_pp"] = run_test_6_no_pp(args)

    elapsed = time.time() - t_start

    print()
    print("=" * 70)
    print("SUMMARY")
    print("=" * 70)
    print(f"  Total runtime: {elapsed / 60:.1f} min")
    if "test_3_bootstrap" in results:
        f1 = np.array(results["test_3_bootstrap"]["F1_zGauss"]["zc"])
        f2 = np.array(results["test_3_bootstrap"]["F2_thGauss"]["thc"])
        print(f"  Test 3 F1 zc:   median = {np.median(f1):.4f}, "
              f"std = {np.std(f1):.4f}    (paper: 0.6380, 0.0692)")
        print(f"  Test 3 F2 thc:  median = {np.median(f2):.4f}, "
              f"std = {np.std(f2):.4f}    (paper: 0.4811, 0.0481)")
    if "test_6_no_pp" in results:
        f1 = np.array(results["test_6_no_pp"]["F1_zGauss"]["zc"])
        f2 = np.array(results["test_6_no_pp"]["F2_thGauss"]["thc"])
        print(f"  Test 6 F1 zc:   median = {np.median(f1):.4f}, "
              f"std = {np.std(f1):.4f}    (paper: 0.6145, 0.2854)")
        print(f"  Test 6 F2 thc:  median = {np.median(f2):.4f}, "
              f"std = {np.std(f2):.4f}    (paper: 0.4820, 0.0091)")

    with open(args.out, "w") as f:
        json.dump(_walk_for_json(results), f, indent=2)
    print(f"  Results written to {args.out}")
    print()
    print("Done.")


if __name__ == "__main__":
    main()
